Page({
  data:{
    // text:"这是一个页面"
    orders:[],
    actved:[],
    ready:[],
    history:[]

    
  },
  onLoad:function(options){
    // 页面初始化 options为页面跳转所带来的参数
    this.getData();
  },

  getData:function(){
    var localData ={
    "success": true,
    "orders": [
        {
            "orderId": 25560,
            "orderNo": "1610171462665",
            "purchasedDays": 7,
            "paymentDate": 1476671963000,
            "startDate": 1476672104000,
            "updateDate": 1476672104000,
            "amount": 700,
            "paymentMethod": 6,
            "orderState": "ACTIVATED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 25558,
            "orderNo": "1610171562213",
            "purchasedDays": 1,
            "paymentDate": 1476671751000,
            "startDate": -1,
            "updateDate": 1476671528000,
            "amount": 990,
            "paymentMethod": 6,
            "orderState": "PURCHASED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53847",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 990,
                "purchasedCount": 8,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(100MB高速)",
                "shortName": "红茶SIM卡-中国测试套餐(100M)",
                "description": "• 套餐提供无限数据流量。其中100MB为4G高速流量，超过后则予以限速;<br>• 第一次激活后套餐开始计时，每24小时计为使用1天。期间无论启用与否会持续计时直至购买天数用完为止；<br>• 购买后需在15天内激活，逾期作废不予退款;<br>• 在境外信号良好区域，该套餐支持无网购买;<br>• 该服务仅支持中国大陆地区。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 25301,
            "orderNo": "1610141535241",
            "purchasedDays": 1,
            "paymentDate": 1476413482000,
            "startDate": 1476348483000,
            "updateDate": 1476435396000,
            "amount": 100,
            "paymentMethod": 6,
            "orderState": "EXPIRED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 25299,
            "orderNo": "1610141894677",
            "purchasedDays": 1,
            "paymentDate": 1476413306000,
            "startDate": -1,
            "updateDate": 1476413149000,
            "amount": 100,
            "paymentMethod": 6,
            "orderState": "REFUNDING",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 25296,
            "orderNo": "1610141835875",
            "purchasedDays": 1,
            "paymentDate": 1476411715000,
            "startDate": -1,
            "updateDate": 1476411907000,
            "amount": 100,
            "paymentMethod": 6,
            "orderState": "REFUNDING",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 23419,
            "orderNo": "1609281437565",
            "purchasedDays": 1,
            "paymentDate": 1475030055000,
            "startDate": -1,
            "updateDate": 1475296147000,
            "amount": 100,
            "paymentMethod": 6,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 23307,
            "orderNo": "1609271427880",
            "purchasedDays": 1,
            "paymentDate": 1474946173000,
            "startDate": -1,
            "updateDate": 1474946401000,
            "amount": 1200,
            "paymentMethod": 3,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53946",
                "locationId": 3,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 990,
                "purchasedCount": 102,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/Taiwan.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/TaiwanFlagNew.png",
                "operator": "Fareastone",
                "netstandard": "2G,3G",
                "name": "台湾包天流量套餐",
                "shortName": "红茶SIM卡-台湾套餐",
                "description": "• 套餐提供无限数据流量。其中300MB为4G高速流量，超过后则予以限速；<br>• 第一次激活后套餐开始计时，每24小时计为使用1天。期间无论启用与否会持续计时直至购买天数用完为止；<br>• 购买后需在15天内激活，逾期作废不予退款；<br>• 在境外信号良好区域，该服务支持无网购买。",
                "locationName": "台湾",
                "mcc": [
                    "466"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 23306,
            "orderNo": "1609271340176",
            "purchasedDays": 1,
            "paymentDate": 1474946140000,
            "startDate": -1,
            "updateDate": 1474946417000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 23297,
            "orderNo": "1609271470570",
            "purchasedDays": 1,
            "paymentDate": 1474944483000,
            "startDate": -1,
            "updateDate": 1474944483000,
            "amount": 1200,
            "paymentMethod": 3,
            "orderState": "RESERVED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53946",
                "locationId": 3,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 990,
                "purchasedCount": 102,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/Taiwan.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/TaiwanFlagNew.png",
                "operator": "Fareastone",
                "netstandard": "2G,3G",
                "name": "台湾包天流量套餐",
                "shortName": "红茶SIM卡-台湾套餐",
                "description": "• 套餐提供无限数据流量。其中300MB为4G高速流量，超过后则予以限速；<br>• 第一次激活后套餐开始计时，每24小时计为使用1天。期间无论启用与否会持续计时直至购买天数用完为止；<br>• 购买后需在15天内激活，逾期作废不予退款；<br>• 在境外信号良好区域，该服务支持无网购买。",
                "locationName": "台湾",
                "mcc": [
                    "466"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 23294,
            "orderNo": "1609271936383",
            "purchasedDays": 1,
            "paymentDate": 1474943742000,
            "startDate": -1,
            "updateDate": 1474946196000,
            "amount": 1200,
            "paymentMethod": 6,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53946",
                "locationId": 3,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 990,
                "purchasedCount": 102,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/Taiwan.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/TaiwanFlagNew.png",
                "operator": "Fareastone",
                "netstandard": "2G,3G",
                "name": "台湾包天流量套餐",
                "shortName": "红茶SIM卡-台湾套餐",
                "description": "• 套餐提供无限数据流量。其中300MB为4G高速流量，超过后则予以限速；<br>• 第一次激活后套餐开始计时，每24小时计为使用1天。期间无论启用与否会持续计时直至购买天数用完为止；<br>• 购买后需在15天内激活，逾期作废不予退款；<br>• 在境外信号良好区域，该服务支持无网购买。",
                "locationName": "台湾",
                "mcc": [
                    "466"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 22540,
            "orderNo": "1609211393286",
            "purchasedDays": 1,
            "paymentDate": 1474448532000,
            "startDate": 1474624558000,
            "updateDate": 1474624558000,
            "amount": 400,
            "paymentMethod": 6,
            "orderState": "EXPIRED",
            "zukAccount": "",
            "dataPlan": {
                "id": "63944",
                "locationId": 1,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 400,
                "purchasedCount": 1,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/HongKong.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/HongkongFlag.png",
                "operator": "CSL",
                "netstandard": "2G,3G",
                "name": "香港",
                "shortName": "EPSIM卡-香港套餐",
                "description": "• 套餐提供无限数据流量。其中300MB为4G高速流量，超过后则予以限速；<br>• 第一次激活后套餐开始计时，每24小时计为使用1天。期间无论启用与否会持续计时直至购买天数用完为止；<br>• 购买后需在15天内激活，逾期作废不予退款；<br>• 在境外信号良好区域，该服务支持无网购买。",
                "locationName": "香港",
                "mcc": [
                    "454"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 18480,
            "orderNo": "1608161964169",
            "purchasedDays": 1,
            "paymentDate": 1471321453000,
            "startDate": -1,
            "updateDate": 1471321739000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "OBSOLETE",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 18479,
            "orderNo": "1608161847161",
            "purchasedDays": 1,
            "paymentDate": 1471321151000,
            "startDate": -1,
            "updateDate": 1471321555000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 15913,
            "orderNo": "1607071778587",
            "purchasedDays": 1,
            "paymentDate": 1467885867000,
            "startDate": -1,
            "updateDate": 1467885867000,
            "amount": 1200,
            "paymentMethod": 4,
            "orderState": "RESERVED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53946",
                "locationId": 3,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 990,
                "purchasedCount": 102,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/Taiwan.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/TaiwanFlagNew.png",
                "operator": "Fareastone",
                "netstandard": "2G,3G",
                "name": "台湾包天流量套餐",
                "shortName": "红茶SIM卡-台湾套餐",
                "description": "• 套餐提供无限数据流量。其中300MB为4G高速流量，超过后则予以限速；<br>• 第一次激活后套餐开始计时，每24小时计为使用1天。期间无论启用与否会持续计时直至购买天数用完为止；<br>• 购买后需在15天内激活，逾期作废不予退款；<br>• 在境外信号良好区域，该服务支持无网购买。",
                "locationName": "台湾",
                "mcc": [
                    "466"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 15888,
            "orderNo": "1607071239856",
            "purchasedDays": 1,
            "paymentDate": 1467873217000,
            "startDate": -1,
            "updateDate": 1468291709000,
            "amount": 1200,
            "paymentMethod": 6,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53946",
                "locationId": 3,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 990,
                "purchasedCount": 102,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/Taiwan.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/TaiwanFlagNew.png",
                "operator": "Fareastone",
                "netstandard": "2G,3G",
                "name": "台湾包天流量套餐",
                "shortName": "红茶SIM卡-台湾套餐",
                "description": "• 套餐提供无限数据流量。其中300MB为4G高速流量，超过后则予以限速；<br>• 第一次激活后套餐开始计时，每24小时计为使用1天。期间无论启用与否会持续计时直至购买天数用完为止；<br>• 购买后需在15天内激活，逾期作废不予退款；<br>• 在境外信号良好区域，该服务支持无网购买。",
                "locationName": "台湾",
                "mcc": [
                    "466"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 15476,
            "orderNo": "1606271302570",
            "purchasedDays": 1,
            "paymentDate": 1466999740000,
            "startDate": -1,
            "updateDate": 1466999768000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "OBSOLETE",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 15475,
            "orderNo": "1606271958582",
            "purchasedDays": 1,
            "paymentDate": 1466999411000,
            "startDate": -1,
            "updateDate": 1466999442000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "OBSOLETE",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 15474,
            "orderNo": "1606271234069",
            "purchasedDays": 1,
            "paymentDate": 1466999205000,
            "startDate": -1,
            "updateDate": 1466999378000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "OBSOLETE",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 15473,
            "orderNo": "1606271542883",
            "purchasedDays": 1,
            "paymentDate": 1466999078000,
            "startDate": -1,
            "updateDate": 1466999244000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "OBSOLETE",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 15424,
            "orderNo": "1606251687076",
            "purchasedDays": 7,
            "paymentDate": 1466848625000,
            "startDate": -1,
            "updateDate": 1466848625000,
            "amount": 17500,
            "paymentMethod": 4,
            "orderState": "RESERVED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53944",
                "locationId": 1,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 990,
                "purchasedCount": 60,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/HongKong.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/HongkongFlag.png",
                "operator": "CSL",
                "netstandard": "2G,3G",
                "name": "香港包天流量套餐",
                "shortName": "红茶SIM卡-香港套餐(润讯)",
                "description": "• 套餐提供无限数据流量。其中300MB高速流量，超过后则予以限速；<br>• 第一次激活后套餐开始计时，每24小时计为使用1天。期间无论启用与否会持续计时直至购买天数用完为止；<br>• 购买后需在15天内激活，逾期作废不予退款；<br>• 在境外信号良好区域，该服务支持无网购买。",
                "locationName": "香港",
                "mcc": [
                    "454"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 15388,
            "orderNo": "1606241692890",
            "purchasedDays": 1,
            "paymentDate": 1466764897000,
            "startDate": -1,
            "updateDate": 1466764897000,
            "amount": 2500,
            "paymentMethod": 4,
            "orderState": "RESERVED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53946",
                "locationId": 3,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 990,
                "purchasedCount": 102,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/Taiwan.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/TaiwanFlagNew.png",
                "operator": "Fareastone",
                "netstandard": "2G,3G",
                "name": "台湾包天流量套餐",
                "shortName": "红茶SIM卡-台湾套餐",
                "description": "• 套餐提供无限数据流量。其中300MB为4G高速流量，超过后则予以限速；<br>• 第一次激活后套餐开始计时，每24小时计为使用1天。期间无论启用与否会持续计时直至购买天数用完为止；<br>• 购买后需在15天内激活，逾期作废不予退款；<br>• 在境外信号良好区域，该服务支持无网购买。",
                "locationName": "台湾",
                "mcc": [
                    "466"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 15384,
            "orderNo": "1606241638925",
            "purchasedDays": 1,
            "paymentDate": 1466763233000,
            "startDate": -1,
            "updateDate": 1466777306000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "OBSOLETE",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14526,
            "orderNo": "1605301157193",
            "purchasedDays": 1,
            "paymentDate": 1464593916000,
            "startDate": -1,
            "updateDate": 1464593916000,
            "amount": 100,
            "paymentMethod": 6,
            "orderState": "RESERVED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53944",
                "locationId": 1,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 990,
                "purchasedCount": 60,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/HongKong.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/HongkongFlag.png",
                "operator": "CSL",
                "netstandard": "2G,3G",
                "name": "香港包天流量套餐",
                "shortName": "红茶SIM卡-香港套餐(润讯)",
                "description": "• 套餐提供无限数据流量。其中300MB高速流量，超过后则予以限速；<br>• 第一次激活后套餐开始计时，每24小时计为使用1天。期间无论启用与否会持续计时直至购买天数用完为止；<br>• 购买后需在15天内激活，逾期作废不予退款；<br>• 在境外信号良好区域，该服务支持无网购买。",
                "locationName": "香港",
                "mcc": [
                    "454"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14525,
            "orderNo": "1605301419945",
            "purchasedDays": 1,
            "paymentDate": 1464751891000,
            "startDate": -1,
            "updateDate": 1464751891000,
            "amount": 100,
            "paymentMethod": 6,
            "orderState": "RESERVED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53946",
                "locationId": 3,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 990,
                "purchasedCount": 102,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/Taiwan.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/TaiwanFlagNew.png",
                "operator": "Fareastone",
                "netstandard": "2G,3G",
                "name": "台湾包天流量套餐",
                "shortName": "红茶SIM卡-台湾套餐",
                "description": "• 套餐提供无限数据流量。其中300MB为4G高速流量，超过后则予以限速；<br>• 第一次激活后套餐开始计时，每24小时计为使用1天。期间无论启用与否会持续计时直至购买天数用完为止；<br>• 购买后需在15天内激活，逾期作废不予退款；<br>• 在境外信号良好区域，该服务支持无网购买。",
                "locationName": "台湾",
                "mcc": [
                    "466"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14417,
            "orderNo": "1605261279294",
            "purchasedDays": 1,
            "paymentDate": 1464250917000,
            "startDate": -1,
            "updateDate": 1464250936000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14416,
            "orderNo": "1605261576790",
            "purchasedDays": 1,
            "paymentDate": 1464250649000,
            "startDate": 1464250614000,
            "updateDate": 1464338229000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "EXPIRED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14385,
            "orderNo": "1605251644936",
            "purchasedDays": 1,
            "paymentDate": 1464173198000,
            "startDate": -1,
            "updateDate": 1464173332000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14384,
            "orderNo": "1605251800756",
            "purchasedDays": 1,
            "paymentDate": 1464173237000,
            "startDate": -1,
            "updateDate": 1464173337000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14383,
            "orderNo": "1605251287118",
            "purchasedDays": 1,
            "paymentDate": 1464172972000,
            "startDate": -1,
            "updateDate": 1464173108000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14382,
            "orderNo": "1605251370647",
            "purchasedDays": 1,
            "paymentDate": 1464172820000,
            "startDate": -1,
            "updateDate": 1464173101000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14381,
            "orderNo": "1605251183164",
            "purchasedDays": 1,
            "paymentDate": 1464172744000,
            "startDate": -1,
            "updateDate": 1464173112000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14380,
            "orderNo": "1605251150138",
            "purchasedDays": 1,
            "paymentDate": 1464172657000,
            "startDate": -1,
            "updateDate": 1464173096000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14379,
            "orderNo": "1605251664500",
            "purchasedDays": 1,
            "paymentDate": 1464172563000,
            "startDate": -1,
            "updateDate": 1464172598000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14378,
            "orderNo": "1605251497472",
            "purchasedDays": 1,
            "paymentDate": 1464172627000,
            "startDate": -1,
            "updateDate": 1464172658000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14377,
            "orderNo": "1605251784518",
            "purchasedDays": 1,
            "paymentDate": 1464172530000,
            "startDate": -1,
            "updateDate": 1464172440000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14376,
            "orderNo": "1605251344949",
            "purchasedDays": 1,
            "paymentDate": 1464172372000,
            "startDate": -1,
            "updateDate": 1464172548000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14375,
            "orderNo": "1605251919017",
            "purchasedDays": 1,
            "paymentDate": 1464172432000,
            "startDate": -1,
            "updateDate": 1464172361000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14374,
            "orderNo": "1605251295758",
            "purchasedDays": 1,
            "paymentDate": 1464172288000,
            "startDate": -1,
            "updateDate": 1464172354000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14373,
            "orderNo": "1605251121390",
            "purchasedDays": 1,
            "paymentDate": 1464172210000,
            "startDate": -1,
            "updateDate": 1464172365000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14372,
            "orderNo": "1605251857808",
            "purchasedDays": 1,
            "paymentDate": 1464172085000,
            "startDate": -1,
            "updateDate": 1464172347000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14369,
            "orderNo": "1605251956311",
            "purchasedDays": 1,
            "paymentDate": 1464171862000,
            "startDate": -1,
            "updateDate": 1464172075000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14368,
            "orderNo": "1605251737307",
            "purchasedDays": 1,
            "paymentDate": 1464171680000,
            "startDate": -1,
            "updateDate": 1464171826000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14367,
            "orderNo": "1605251290734",
            "purchasedDays": 1,
            "paymentDate": 1464171732000,
            "startDate": -1,
            "updateDate": 1464171832000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14366,
            "orderNo": "1605251212362",
            "purchasedDays": 1,
            "paymentDate": 1464171508000,
            "startDate": -1,
            "updateDate": 1464171837000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14365,
            "orderNo": "1605251551929",
            "purchasedDays": 1,
            "paymentDate": 1464171449000,
            "startDate": -1,
            "updateDate": 1464171820000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14364,
            "orderNo": "1605251302985",
            "purchasedDays": 1,
            "paymentDate": 1464171310000,
            "startDate": -1,
            "updateDate": 1464171375000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14363,
            "orderNo": "1605251473344",
            "purchasedDays": 1,
            "paymentDate": 1464171401000,
            "startDate": -1,
            "updateDate": 1464171388000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14362,
            "orderNo": "1605251151646",
            "purchasedDays": 1,
            "paymentDate": 1464171277000,
            "startDate": -1,
            "updateDate": 1464171495000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14361,
            "orderNo": "1605251482150",
            "purchasedDays": 1,
            "paymentDate": 1464171180000,
            "startDate": -1,
            "updateDate": 1464171128000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14358,
            "orderNo": "1605251197341",
            "purchasedDays": 1,
            "paymentDate": 1464169876000,
            "startDate": -1,
            "updateDate": 1464170814000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14357,
            "orderNo": "1605251599513",
            "purchasedDays": 1,
            "paymentDate": 1464169244000,
            "startDate": -1,
            "updateDate": 1464169516000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14356,
            "orderNo": "1605251318898",
            "purchasedDays": 1,
            "paymentDate": 1464168919000,
            "startDate": -1,
            "updateDate": 1464169170000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14354,
            "orderNo": "1605251477134",
            "purchasedDays": 1,
            "paymentDate": 1464168565000,
            "startDate": -1,
            "updateDate": 1464168860000,
            "amount": 100,
            "paymentMethod": 4,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14338,
            "orderNo": "1605251127764",
            "purchasedDays": 1,
            "paymentDate": 1464148207000,
            "startDate": 1464155992000,
            "updateDate": 1464235809000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "EXPIRED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53946",
                "locationId": 3,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 990,
                "purchasedCount": 102,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/Taiwan.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/TaiwanFlagNew.png",
                "operator": "Fareastone",
                "netstandard": "2G,3G",
                "name": "台湾包天流量套餐",
                "shortName": "红茶SIM卡-台湾套餐",
                "description": "• 套餐提供无限数据流量。其中300MB为4G高速流量，超过后则予以限速；<br>• 第一次激活后套餐开始计时，每24小时计为使用1天。期间无论启用与否会持续计时直至购买天数用完为止；<br>• 购买后需在15天内激活，逾期作废不予退款；<br>• 在境外信号良好区域，该服务支持无网购买。",
                "locationName": "台湾",
                "mcc": [
                    "466"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14335,
            "orderNo": "1605251114081",
            "purchasedDays": 1,
            "paymentDate": 1464144558000,
            "startDate": -1,
            "updateDate": 1464168326000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "REFUNDED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14311,
            "orderNo": "1605241743215",
            "purchasedDays": 1,
            "paymentDate": 1464064394000,
            "startDate": 1464064384000,
            "updateDate": 1464145502000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "EXPIRED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14310,
            "orderNo": "1605241898543",
            "purchasedDays": 1,
            "paymentDate": 1464062168000,
            "startDate": 1464062384000,
            "updateDate": 1464149406000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "EXPIRED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53946",
                "locationId": 3,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 990,
                "purchasedCount": 102,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/Taiwan.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/TaiwanFlagNew.png",
                "operator": "Fareastone",
                "netstandard": "2G,3G",
                "name": "台湾包天流量套餐",
                "shortName": "红茶SIM卡-台湾套餐",
                "description": "• 套餐提供无限数据流量。其中300MB为4G高速流量，超过后则予以限速；<br>• 第一次激活后套餐开始计时，每24小时计为使用1天。期间无论启用与否会持续计时直至购买天数用完为止；<br>• 购买后需在15天内激活，逾期作废不予退款；<br>• 在境外信号良好区域，该服务支持无网购买。",
                "locationName": "台湾",
                "mcc": [
                    "466"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14286,
            "orderNo": "1605231919230",
            "purchasedDays": 1,
            "paymentDate": 1463972625000,
            "startDate": 1464005748000,
            "updateDate": 1464070398000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "EXPIRED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14282,
            "orderNo": "1605231371296",
            "purchasedDays": 1,
            "paymentDate": 1463970553000,
            "startDate": 1463970875000,
            "updateDate": 1464057160000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "EXPIRED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14227,
            "orderNo": "1605201288838",
            "purchasedDays": 1,
            "paymentDate": 1463743661000,
            "startDate": 1463918986000,
            "updateDate": 1464005820000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "EXPIRED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        },
        {
            "orderId": 14226,
            "orderNo": "1605201302736",
            "purchasedDays": 1,
            "paymentDate": 1463743588000,
            "startDate": 1463743708000,
            "updateDate": 1463744341000,
            "amount": 100,
            "paymentMethod": 3,
            "orderState": "EXPIRED",
            "zukAccount": "",
            "dataPlan": {
                "id": "53848",
                "locationId": 5,
                "duration": 1,
                "type": 1,
                "dataVolume": -1,
                "promoPrice": null,
                "price": 100,
                "purchasedCount": 111,
                "expirationDays": 15,
                "minDays": 1,
                "maxDays": 7,
                "promoBannerUrl": null,
                "coverUrl": "http://images.redteamobile.com/images/locations/covers/China.jpg",
                "status": "ACTIVE",
                "logoUrl": "http://images.redteamobile.com/images/locations/logos/ChinaFlag.png",
                "operator": "ChinaUnicom",
                "netstandard": "2G,3G",
                "name": "中国测试套餐(4G)(10M)",
                "shortName": "红茶SIM卡-中国套餐(4G)",
                "description": "本套餐为4G网络套餐。本套餐用于国内测试,每个订单只有10MB可用流量，流量用尽后则无法上网。",
                "locationName": "中国大陆",
                "mcc": [
                    "460"
                ],
                "directedApps": []
            }
        }
    ]
    };
    var orderArr = localData.orders;
    this.getGroupArr(orderArr);

  },
  
  getGroupArr:function(orders){
      var dataArr = [];
      var inactiveArr = [];
      var activateArr = [];
      var historyArr = [];
      for(var i=0;i<orders.length;i++){
          var order = orders[i];
          if(order.orderState == 'ACTIVATED'){
              order.orderState ='已激活';
              order.startDate = this.convertToReadyTimeStr(order);
              activateArr.push(order);
          }else if(order.orderState == 'PURCHASED'){
              order.orderState ='未激活';
              order.startDate = this.convertToActiveTimeStr(order);
              inactiveArr.push(order);
          }else if(order.orderState != 'RESERVED'){
              var state = '';
              if(order.orderState =='REFUNDED'){
                  order.orderState = '已退款';
              }else if(order.orderState =='EXPIRED'){
                  order.orderState = '已使用';
              }else if(order.orderState =='OBSOLETE'){
                  order.orderState = '已过期';
              }else if(order.orderState =='REFUNDING'){
                  order.orderState = '申请退款中';
              }
              historyArr.push(order);
          }

      }
    this.setData({actved:activateArr,ready:inactiveArr,history:historyArr});
     

  },

  convertToReadyTimeStr:function(order){
    //获取当前时间戳
    var timestamp = Date.parse(new Date());
    var second = (60 * 60 * 24 * 1000 * order.purchasedDays - (timestamp - order.startDate)) / 1000;
  
    var days =   parseInt(second / (3600 * 24));
    var hours=   parseInt(second%(3600*24)/3600);
    var mins =   parseInt((second / 60 ) % 60);
    var tStr = '剩余';
    if(days > 0){
       tStr = tStr + days +'天';
    }
    if(hours > 0){
       tStr = tStr + hours +'小时';
    }
    if(mins > 0){
       tStr = tStr + mins +'分钟';
    }
    console.log(tStr);
    return tStr;
  

  },

  convertToActiveTimeStr:function(order){
     //获取当前时间戳
   
    var buyDate = order.paymentDate;
    var expirationDays = order.dataPlan.expirationDays * 24 * 60 * 60 *1000;
    var time = buyDate + expirationDays ;

    // var newDate = new Date();
    // newDate.setTime(time );
    // Wed Jun 18 2014 
    // console.log(newDate.toLocaleTimeString());
    // Wed, 18 Jun 2014 02:33:24 GMT  

    var date = new Date(time);
    var Y = date.getFullYear() + '-';
    var M = (date.getMonth()+1 < 10 ? '0'+(date.getMonth()+1) : date.getMonth()+1) + '月';
    var D = date.getDate() + '日 ';
    var h = date.getHours() + ':';
    var m = date.getMinutes() + ' ';
    var s = date.getSeconds(); 
    console.log(Y+M+D+h+m+s); //呀麻碟
    var tStr = '请于北京时间' + M+D+h+m + '前激活';
    return tStr;
  },

  onReady:function(){
    // 页面渲染完成
  },
  onShow:function(){
    // 页面显示
  },
  onHide:function(){
    // 页面隐藏
  },
  onUnload:function(){
    // 页面关闭
  }
})